name: Check JSON

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v3

      - name: Install mc-build
        run: npm i -g mc-build
      - name: Run mc-build
        run: mcb -build

      - name: json-lint
        uses: ocular-d/json-linter@0.0.2
